### ISSUE TITLE
Document how phonegap-app-developer can be used with Cordova

### ISSUE THREAD

**Issue by slorber** [phonegap/phonegap-app-developer#135]
Hello,

Until now I was able to use phonegap-app-developer with `cordova serve`.
It worked fine until I did an Ajax but there used to be a bug with CORS and a need for a proxy: https://github.com/phonegap/phonegap-app-developer/issues/98

This proxy seems to have been implemented in Phonegap CLI but not in Cordova CLI

It would be nice to document if phonegap-app-developer can be used with a Cordova project.

Actually my project is a cordova project and it seems I'm able to use it (with the proxy) by creating an empty `.cordova` folder and running `phonegap serve` instead of `cordova serve`

Which is confusing because I was told by a Cordova dev to use cordova CLI unless I need Phonegap Build system, but it seems the Phonegap CLI is not only cordova + the build system commands

**Comment by EeKay** [comment]
I believe the command has been implemented so that the cordova serve command can be used in conjunction with the "browser" target platform to run the www on a localhost server instance.. at least that's its purpose for me.

This enables devs to quickly check out if the weblayer is working in combination with plugins that have (test) implementations for the browser target as well...

**Comment by surajpindoria** [comment]
Closing this out, we have documented how to use the [correct commands](https://github.com/phonegap/phonegap-app-developer#compile-and-run) for the app.
