### ISSUE TITLE
Ajax calls fail - is it because URL is http://phonegap-serve-ip and not file://some-local-file?

### ISSUE THREAD

**Issue by jornklung** [phonegap/phonegap-app-developer#169]
Hi,
PhoneGap App Developer is a great concept - got it up and running.
However there seems to be an inherint problem with doing Ajax calls/requests.
We have an app that catches content from a server.
This works fine when running the app as an installed app as the URL is file://some-local-file
BUT when running it with PhoneGap App Developer the URL becomes the URL of the phonegap server which PhoneGap App Developer is connected to.
When doing the AJAX calls they get rejected due to what seems like cross domain requests.
Do you have any suggestion on how to solve this problem?
Thanx for a great product and service!
Jørn

**Comment by souhailalavi** [comment]
Hi, We are developing a project using phonegap for iOS and Android.

One of the features we implemented depends on calling another page from within the phonegap project using ajax. This works fine on iOS and Android 4.0, however due to the Android Lolipop using Chrome as a default browser, now our links dont work and we get a CORS error.

XMLHttpRequest cannot load file:///Users/sou/login%20page/www/restodetails.html. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

Android 5.0 was just realeased a few months ago and now we have to fix this issue. Has anymore come across an issuel ike this loading another file from within the app?

Please help!

**Comment by mwbrooks** [comment]
Hi @souhailalavi,

By the sounds of it, this isn't a PhoneGap Developer App issue (directly). I've just spoke with @infil00p and he suggested that this issue may have been resolved in the latest Cordova Android release, which coincidently came out on Friday. If you're building the Android app locally, then you can try to upgrade to Cordova Android 3.7.0, which apparently disables CORS by default. However, the PhoneGap Developer App is running Cordova Android 3.6.x, so you'll still experience the CORS issue with it.

You can install the latest Cordova Android with:

    $ cd my-app/
    $ phonegap platform add android@3.7.0
    $ phonegap run android

Cheers,
Michael

**Comment by snow01** [comment]
I am also facing the exact same issue as @whitecolor and @jornklung mentioned above.

Probably it is an issue with phonegap developer app ?

**Comment by shohoku11wrj** [comment]
I wondering if there is any solution for simple Ajax cross site GET request in HTML5 app using PhoneGap?

    $.ajax({
                url: "some api request",
                headers: {"Content-Type":"application/json; charset=UTF-8"},
                data: jsonData,
                dataType: "json",
                method: 'GET',
                success: function( data ) {
                    $("#pname").html(data);
                }
            });

**Comment by timkim** [comment]
With the 1.5.2 release, AJAX calls should now work like it normally does in a PhoneGap app.
