### ISSUE TITLE
I can't pair my wp8 with phonegap serve

### ISSUE THREAD

**Issue by mrodrigolira** [phonegap/phonegap-app-developer#230]
Hi, i'm a new phonegap developer and i have the CLI working like a charm. I've tested it building some apps without error, but when i tried to pair the phone with phonegap developer app it doesn't work.

The app returned an "error" then "timed out" and i opened the phonegap server on my browser and it worked.

I've checked the phonegap serve ip and it's the same as my machine. Both my machine as my windows phone are on the same network. 

I'm using phonegap version 3.6.0-0.21.19.

**Comment by HumayunE** [comment]
Hi @mrodrigolira
I am having the same problem as yours, but i am using phonegap desktop app beta 0.1.1, i don't know what should i have to do, i am new to phonegap.

**Comment by mwbrooks** [comment]
@mrodrigolira @HumayunE Occasionally, I've found that the incorrect IP Address is provided by the PhoneGap CLI (and PhoneGap Desktop App). This sometimes happens when you have more than one network adapter or a virtual network adapter with an assigned IP address (e.g. Windows Phone Simulator or a Virtual Machine).

I've patched this issue in the more recent versions of `connect-phonegap`, which is used by the more recent versions of the `phonegap-cli`. Unfortunately, the PhoneGap Desktop App is still using an older version.

@mrodrigolira could you try updating to the latest PhoneGap CLI and try to pair with the Developer App? If the pairing fails again, can you provide me with the IP address output by the CLI and also the output of running `ipconfig` in your terminal/Command Prompt?

Thanks!

**Comment by mwbrooks** [comment]
Closing since we haven't seen very much activity on this issue. Feel free to reopen.
