### ISSUE TITLE
Dev App throws error after change made to file

### ISSUE THREAD

**Issue by CCDSystems** [phonegap/phonegap-app-developer#259]
PhoneGap dev app working fine for me (win7), but after making a change to a file, I see the following in the dev app screen:

Uncaught node.js Error

Error: watch EPERM
at exports._errnoException (util.js:742:11)
at FSEvent.FSWatcher._handle.onchange (fs.js:1045:26)

**Comment by timkim** [comment]
Hi there @CCDSystems 

Just tested on my windows machine and it seems fine there. What version of `phonegap` are you running? If you aren't on `4.1.2-0.22.12`, you might want to try and upgrade `phonegap` by doing `npm install -g phonegap`. 

Otherwise, it seems like you're running into a permission issue. You might want to try running the command prompt or your git bash as an administrator and then try again. Let me know if that helps.

**Comment by mwbrooks** [comment]
Closing since we haven't seen very much activity on this issue. Feel free to reopen.
