### ISSUE TITLE
3-finger and 4-finger gestures don't work on 404s

### ISSUE THREAD

**Issue by ptarjan** [phonegap/phonegap-app-developer#260]
If I end up on a 404 page, the gestures stop working.

**Comment by timkim** [comment]
Hi @ptarjan,

This is a known issue and is related to https://github.com/phonegap/phonegap-app-developer/issues/94. Basically, the gesture js files which are sent from the server to the phone won't be sent in the case of a 404. Right now, there is no fix other than reseting the app (ie, quit and re-open). 

We're currently working on a new method of serving the files (https://github.com/phonegap/phonegap-plugin-contentsync/) to the app so that approach could fix this problem but won't be out for a bit. We will let you know once we have a fix!

**Comment by darkyen** [comment]
@timkim why can't you just poll in case of 404 ?

**Comment by purplecabbage** [comment]
this is a challenging issue.
In the near future we are re-architecting to address a whole category of issues, including this one.
