### ISSUE TITLE
Having a problem in pairing my android mobile with phonegap desktop app beta 0.1.1

### ISSUE THREAD

**Issue by HumayunE** [phonegap/phonegap-app-developer#264]
I am using phonegap desktop app beta 0.1.1 and trying to pair my android phone, when i tried to pair the phone with phonegap developer app it doesn't work.
The app returned an "error" then "timed out" and then i tried to open the phonegap server on my browser and it worked.
I've checked the phonegap server ip and it's the same as my machine. Both my machine and my android mobile are on the same network. I don't know what should i have to do, i am new to phonegap please help.

**Comment by timkim** [comment]
Hi @HumayunE 

You may want to post this in the phonegap desktop app issue tracker instead of here: https://github.com/phonegap/phonegap-app-desktop

But I will try to help :) 

Which os are you running on? Also, once you start up the phonegap desktop app, hit the console button and see if your phone is actually able to request form the server. If the server logs are bare, it's most likely that your problem is a network issue.

**Comment by HumayunE** [comment]
i am using windows 7..and yup!! the server logs are bare.. :(

**Comment by timkim** [comment]
Hrm, you might wanna see if you can actually ping devices connected to your network. 

1) Get the ip address of your phone that's connected to your network
2) On your windows machine, hit Windows Key + R and then type in `cmd` to get the command prompt (or go to Start Menu -> Run -> type `cmd')
3) type `ping <ip-address of your phone>`

If those pings time out, it is likely you can't send information between ip's on your network. At that point, you'll have to configure your router settings or turn off your firewall.

**Comment by mwbrooks** [comment]
Closing since we haven't seen very much activity on this issue. Feel free to reopen.
