### ISSUE TITLE
no nfc detected with the app.

### ISSUE THREAD

**Issue by VanHumbeeckA** [phonegap/phonegap-app-developer#289]
I'm using the phonegap-nfc plugin, on an Android device, Nexus 5. The plugin works when i build it, but it doesn't work when using the phonegap app. Is the app missing dependencies to nfc hardware?

**Comment by mwbrooks** [comment]
Hi @VanHumbeeckA,

Unfortunately, the PG Developer App does not currently support third-party plugins. This is a technical issue that we're trying to overcome, since a plugin with a native implementation must be compiled. Any suggestions are welcome!

At the moment, you'll need to build to a simulator or device. Sorry about that!
