### ISSUE TITLE
Can't use "DNS Soa Serial number format" as Android versionCode 

### ISSUE THREAD

**Issue by pa-de-solminihac** [phonegap/phonegap-app-developer#326]
If you use the **DNS Soa Serial number format** format (ie. _YYYYmmddss_) as your Android `versionCode` it will be too big for an integer value, as the `platforms/android/build.gradle` script suffixes it with a "0".

For example, today's `versionCode` could be 2015062301.

The build script will suffix it with a "0", and cast it as an integer. So it becomes `20,150,623,010` but its too high for and integer, whose max value is `2,147,483,647`.

Then the build script fails.

**Worst part** : it used to work, so I can't upgrade my apps on Google Play !

**Comment by pa-de-solminihac** [comment]
Hi @timkim 

Is there a reason why you add this + "0" ?

**Comment by timkim** [comment]
Hi @pa-de-solminihac 

You know, I wasn't sure why it added 0's myself. I asked some people on the Cordova team and they weren't sure either. It seems that the person who implemented that particular function did so without documenting why. 

You might try the [cordova issue tracker](https://issues.apache.org/jira/browse/CB/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel) and raising this issue there since this isn't really a `phonegap-app-developer` issue.
