### ISSUE TITLE
WP8 splash screen flickers on load

### ISSUE THREAD

**Issue by timkim** [phonegap/phonegap-app-developer#349]
I have a feeling that one of perhaps some of the config preferences are causing a flicker on load. Will have to look into this.

**Comment by mwbrooks** [comment]
#### My Device

- Lumia 920 WP 8.1

#### App Configuration

Cordova WP 3.8.1

```
<preference name="AutoHideSplashScreen" value="false" />
```

We call `navigator.splashscreen.hide();` after the app is fully initialized.

#### Problem Description

When compiled in release mode and run with the VS debugger attached:
- I see our black splash screen (correct)
- I see a quick flicker of a white screen or our app - varies (incorrect)
- I see the black splash screen (correct)
- I see splash screen disappear and display the app (correct)

When compiled in release and run _detached from USB debugger_:
- I see our black splash screen (correct)
- _I see a quick flicker our app that is half faded out (incorrect)_
- I see the black splash screen (correct)
- I see splash screen disappear and display the app (correct)

#### Debugging Attempts

- I've downgraded the splash screen and tried:
  - `2.1.0`
  - `2.0.0`
  - `1.0.0`
  - `0.3.5`
  - `0.3.4`
  - `0.3.3`
  - `0.3.2`
  - `0.3.1`
  - `0.3.0`
- If I downgrade to `0.3.0` then the `AutoHideSplashScreen` preference is not supported by WP.
  - At this point, the splash screen acts correctly.
- I've removed the `navigator.splashscreen.hide();`
  - The splash screen remains displayed. This is correct.

**Comment by mwbrooks** [comment]
I think we will need @purplecabbage to investigate whether this is a WP8 Splash Screen issue.

**Comment by purplecabbage** [comment]
Short-term fixes:
1. Copy the splashscreen image you want to use to platforms/wp8/SplashScreenImage.jpg ( make sure it is jpg and 768x1280 )
2. modify splashscreen.cs to return null from GetSplashScreenImageResource(). You can do this by forking the repo and installing from the fork, or you can modify the file in your WP8 build scripts.

The flash happens because WP8 has a default handling of a splashscreen using the image "SplashScreenImage.jpg" which is shown before any of our code loads.
Then our code looks thru config for the file path ( or uses default ) creates an image and puts it on screen.
We have no control over the gap in time from OS splashscreen to our code and splashscreen.

As an alternative to 2. You may want to simply make the build script remove the splashscreen plugin on the wp8 platform.

**Comment by mwbrooks** [comment]
Nice, thanks @purplecabbage.

We went with your short-term fix, which was to manually copy the `SplashScreenImage.jpg` and modify `SplashScreen.cs` to return null. We were able to accomplish this with a small hook that runs quick.
