### ISSUE TITLE
cp: no such file or directory: cordova-lib/node_modules/cordova-app-hello-world/hooks/*

### ISSUE THREAD

**Issue by LoLei** [phonegap/phonegap-app-developer#363]
Trying to create the hello world app via the guide. 

After step `phonegap create myApp`:
```
$ phonegap create myApp
Creating a new cordova project.
cp: no such file or directory: /usr/local/lib/node_modules/phonegap/node_modules/cordova-lib/node_modules/cordova-app-hello-world/hooks/*
cp: no such file or directory: /usr/local/lib/node_modules/phonegap/node_modules/cordova-lib/node_modules/cordova-app-hello-world/config.xml
```

The folder still gets created with contents.

```
$ cd myApp 
$ phonegap serve
$
```

But nothing happens on `phonegap serve` and I can't connect on the mobile app.

I have cordova installed.

OS: Elementary OS
Recent install of nodejs, phonegap and cordova.

**Comment by mwbrooks** [comment]
Hi @LoLei,

Unfortunately, you had bad timing since Node v5.0.0 cause an internal issue with one of our libraries. We've fixed the issue in `phonegap@5.3.7`.

See https://github.com/phonegap/phonegap-cli/issues/560#issuecomment-154740961 for more details.

Thanks for reporting the issue and let me know if upgrading doesn't solve your problem!
Michael
