### ISSUE TITLE
Disable phonegap hidden gestures

### ISSUE THREAD

**Issue by equilerex** [phonegap/phonegap-app-developer#414]
im trying to build a game using phonegap but the "hidden gestures" of the developer app (3 finger tap to go back & 4 fingers for going to main menu) basically make it impossible to test it... any way of turning it off?

**Comment by timkim** [comment]
Hi @equilerex 

There's no configurable option right now to turn it off. I can add it as a feature in [connect-phonegap](https://github.com/phonegap/connect-phonegap), but I'm unsure when that will land. 

However, if you want to do something a _little_ hacky to turn it off, you can try the following:
1. Locate where you have installed the node module: `phonegap-cli' 
2. Browse into its file directory and find these files:

`phonegap/node_modules/connect-phonegap/res/middleware/homepage.js`
`phonegap/node_modules/connect-phonegap/res/middleware/refresh.js`
3. Edit those files and just delete the *contents*, but make sure the files still exist. 
4. Try to `phonegap serve` your app and I believe that should turn off the hidden gestures. 

In the mean time, I've created an issue to track this in `connect-phonegap`: https://github.com/phonegap/connect-phonegap/issues/151

**Comment by equilerex** [comment]
@timkim worked like a charm! thanks a lot ;)

**Comment by rgliberty** [comment]
Hey guys, I'm using the Desktop App on Windows 10 and would love to know if there is a _hack _way to turn off those gestures without the CLI, as I don't have those directories listed by @timkim .

I'm developing a app for a toddler, and lets just say... it's difficult to test when they use a minimum of 5 fingers to do anything on screen.

Thanks!

**Comment by timkim** [comment]
Hi @rgliberty 

It would be _possible_ to do on the Desktop App, but I would not recommend going down that route. I don't know how the Desktop App is all built off the top of my head, but I would assume the steps would have to be:
1. Modify your own `connect-phonegap` module like I did above
2. Fork your own `phonegap-cli` so that its `package.json` points to the `connect-phonegap` repo with the modifications
3. Fork the Desktop App repo and point its dependency to the modified `phonegap-cli`.
4. Build and compile the Desktop App

Seems like it would be pretty error prone at that point.

**Comment by timkim** [comment]
Hello all,

I've added support to optionally include *any* of the injectable scripts. Simply update the `phonegap-cli@6.3.0` by going `npm install -g phonegap`. 

And when you are serving, you can supply commands like:
```
$ phonegap serve --no-homepage --no-refresh --no-autoreload // turns off 3/4 finger tap and autoreload
```

See `$ phonegap serve --help` for a full list of options.
