### ISSUE TITLE
window.location.href = "/" does not work in 1.7.9

### ISSUE THREAD

**Issue by devBarn** [phonegap/phonegap-app-developer#492]
So we have previously had 1.3 which redirected fine to the root of the application however when we upgraded to 1.7.9 this caused this redirect to fail. To get around this I pointed the window.location.href to index.html.

**Comment by timkim** [comment]
Hi @devBarn 

So since 1.3 (almost three years ago!), we have added the content sync plugin which changes how the files are sent to the developer app. You won't be able to use `window.location.href = "/" ` because we are actually sending your entire project to the developer app as a zip. For example the index.html now lives at the url: `file:///data/user/0/com.phonegap.app.adhoc/files/phonegapdevapp/www/index.html`

See this for more info: https://github.com/phonegap/phonegap-plugin-contentsync#working-with-the-native-file-system

**Comment by devBarn** [comment]
Hi @timkim,

Thank you so much for your quick response. I thought that there must have been a big change in the way the application works because the load times are so different with 1.3 being almost instant.

Thank you for this information and the link. It has helped a lot for this project and will no doubt help with future projects.

Best wishes,

Barns
